#
# pll.awk, generate code to program
# the sdram pll (pll2)...
#
# uses the config file to get the correct
# parameters...
#
/^DEVICE/ {
  device = $2;
}

END {
   printf("/* asm.S, automatically generated by asm.awk...\n */\n");
   if (device == "epxa1") {
       print ".set EPXA_IDCODE, 0x081010dd";
   }
   else if (device == "epxa4") {
       print ".set EPXA_IDCODE, 0x084010dd";
   }
   else if (device == "epxa10") {
       print ".set EPXA_IDCODE, 0x090010dd";
   }
}


