#
# pll.awk, generate code to program
# the sdram pll (pll2)...
#
# uses the config file to get the correct
# parameters...
#
BEGIN {
  ahb1 = 0;
  external = 0;
  regs = 0;
}

/^REGISTERS/ {
  regs = numericValue($2);
}

/^AHB1/ {
  ahb1 = numericValue($2);
}

/^SDRAM_CLK/ {
  sdram = numericValue($2);
}

/^EXTERNAL/ {
  external = numericValue($2);
}

/^DEVICE/ {
  device = $2;
}

END {
   printf("/* epxa.h, automatically generated by epxa.awk...\n */\n");
   printf("#ifndef EPXA_HEADER\n#define EPXA_HEADER\n\n");
   
   if (regs!=0) printf("#define REGISTERS 0x%x\n", regs);
   if (ahb1!=0) printf("#define AHB1 %u\n", ahb1);
   
   
   printf("\n#endif\n");
}
