#
# pte.awk, initialize page tables, transfer control...
#
# uses the config file to get the correct
# parameters...
#
BEGIN {
  #
  # by default, page tables are invalid...
  #
  for (i=0; i<4096; i++) ptes[i] = numericValue("0");
}

/^PTE/ {
   virt = rshift(numericValue($2), 20);
   phys = numericValue($3);
   size = numericValue($4);
   
   if ( $5 == "none" )     { access = 0; }
   else if ( $5 == "clnt") { access = 1; }
   else if ( $5 == "res")  { access = 2; }
   else if ( $5 == "mgr")  { access = 3; }
   else {
      printf("invalid access value: '%s'\n", $5);
      exit(1);
   }
   
   domain = numericValue($6);
   
   if ( $7 == "NCNB" )     { cache = 0; }
   else if ( $7 == "NCB" ) { cache = 1; }
   else if ( $7 == "WT" )  { cache = 2; }
   else if ( $7 == "WB" )  { cache = 3; } 
   else {
      printf("invalid cache attribute: '%s'\n", $7);
      exit(1);
   }

   for (i=virt; i<virt+size; i++) {
      # what is this? lisp?
      ptes[i] = or(2,
		   or(lshift(cache, 2), 
		      or(lshift(1, 4),
			 or(lshift(domain, 5),
			    or(lshift(access, 10),
			       phys)))));
   }
}

END {
  printf("\t#\n\t# autogenerated by pte.awk...\n\t#\n");
  for (i=0; i<4096; i++) {
     printf("\t.word\t0x%08x\n", ptes[i]);
  }
}
